services:
  redis:
    container_name: redis
    image: redis:6.2.6-bullseye
    ports:
    - 6379:6379
    # COPY redis.conf /usr/local/etc/redis/redis.conf

  redislabdotnet:
    container_name: redislab-web
    image: redislabdotnet/webclient
    build:
      context: .
      dockerfile: RedisLabDotNet/Dockerfile

  #sampleone:
  #  container_name: sampleone-console
  #  image: redislabdotnet/sampleone-console
  #  build:
  #    context: .
  #    dockerfile: SampleOne/Dockerfile
  
    